# Generated by Django 5.2.10 on 2026-09-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0006_alter_order_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_available",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
