# Generated by Django 5.2.10 on 2026-09-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("vendor", "Vendor"),
                    ("customer", "Customer"),
                    ("social", "Social"),
                ],
                default="customer",
                max_length=32,
            ),
        ),
    ]
